# Generated by Django 2.2.5 on 2019-09-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190910_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='typeofpost',
            field=models.CharField(choices=[('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.')], default='', max_length=3),
        ),
    ]
