# Generated by Django 2.2.5 on 2019-09-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_typeofpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='typeofpost',
        ),
        migrations.AddField(
            model_name='post',
            name='horror_type',
            field=models.CharField(choices=[('PSY_HORROR', 'Psychological horror'), ('ALIENS', 'Alien'), ('INESCAPABLE', 'Inescapable'), ('PERSONAL', 'Personal Horror'), ('MYTH', 'Horror Myth'), ('GHOST', 'Ghost Horror'), ('ZOMBIE', 'Zombies'), ('H_H', 'Haunted House')], default='Horror', max_length=3),
        ),
    ]
