# Generated by Django 2.2.5 on 2019-09-13 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0012_auto_20190911_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='horror_type',
            field=models.CharField(choices=[('PSYCHOLOGICAL HORROR', 'Psychological horror'), ('ALIEN', 'Alien'), ('INESCAPABLE', 'Inescapable'), ('PERSONAL HORROR', 'Personal Horror'), ('HORROR MYTH', 'Horror Myth'), ('GHOST HORROR', 'Ghost Horror'), ('ZOMBIE', 'Zombies'), ('HAUNTED HOUSE', 'Haunted House')], default='Horror', max_length=50),
        ),
        migrations.CreateModel(
            name='lists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(default='default.jpg', upload_to='post_pics')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
