# Generated by Django 2.2.5 on 2019-09-13 11:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0013_auto_20190913_1657'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='lists',
            new_name='list',
        ),
    ]
