# Generated by Django 2.2.5 on 2019-09-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190913_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='content',
        ),
        migrations.AddField(
            model_name='list',
            name='item1',
            field=models.CharField(default='ewq', max_length=200),
        ),
        migrations.AddField(
            model_name='list',
            name='item2',
            field=models.CharField(default='eqw', max_length=200),
        ),
        migrations.AddField(
            model_name='list',
            name='item3',
            field=models.CharField(default='eqw', max_length=200),
        ),
    ]
