# Generated by Django 2.2.5 on 2019-09-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20190913_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='list',
            name='item1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='list',
            name='item2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='list',
            name='item3',
            field=models.CharField(default='', max_length=200),
        ),
    ]
